Repository nihilistdbanana/python-training, pull requests merged in 2023-10, with the labels that each got.

#19 Create Problem_001
  VidishaPandey/Problem_001
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#20 Create Problem_002
  VidishaPandey/Problem_002
Labels: hacktoberfest-accepted, hacktoberfest

#21 Update Problem_002
  VidishaPandey/Problem_002
Labels: hacktoberfest-accepted, hacktoberfest

#22 Update Problem_002
  VidishaPandey/Problem_002
Labels: hacktoberfest-accepted, hacktoberfest

#23 Update Problem_002
  VidishaPandey/Problem_002
Labels: hacktoberfest-accepted, hacktoberfest

#30 Solution for Problem 2, of 2nd file.
  HitanshuSingh/Problem02--2.py
Labels: hacktoberfest-accepted

#31 Solution for 1st problem, of 2nd file.
  HitanshuKSingh/Problem02--1.py
Labels: hacktoberfest-accepted
